### ISSUE TITLE
Support opening files without extensions

### ISSUE THREAD

**Issue by Sanqui** [dbarenholz/obsidian-plaintext#16] opened 2023-07-27 13:23 UTC
On Linux, it is customary (if unfortunate) to leave text files without any extension (such as plain `README` instead of `README.txt`).  Currently, the plugin appear to support opening files with no extension.

**Comment by dbarenholz** [comment] 2023-08-25 19:56
Duplicate of https://github.com/dbarenholz/obsidian-plaintext/issues/9

**Closed by dbarenholz** 2023-08-25 19:56 UTC
