### ISSUE TITLE
Regular .txt files

### ISSUE THREAD

**Issue by Aurocosh** [dbarenholz/obsidian-plaintext#11] opened 2022-11-25 14:51 UTC
Hello. For some reason this plugin doesn't work with regular .txt files. It works with all other extensions that i tested. Furthermore .txt extension gets deleted from plugin options whenever i leave them. It doesn't work even with "Destroy other plugins" options turned on.

Is this a bug? Or is .txt not supported for some kind of technical reason?

Just in case here is the current list of my plugins: Advanced Tables, Obsidian Git, Plaintext, Tasks.

**Comment by valgameiroconsulting** [comment] 2023-02-15 16:51
I have a similar problem. I'm on Windows 10 and Ubuntu 22.04 LTS, and every time I try to open a .txt file it opens up in my text editor, not Obsidian. If I change the extension to .text it works, but .txt does not. It clears it out of the setting field even.

**Comment by hacks2learn** [comment] 2023-04-19 11:59
I discovered the same problem in Linux but I found a workaround:

**Solution**:  Update the file :  `.obsidian/plugins/obsidian-plaintext/main.js`
Comment out the line : `["txt-as-md-obsidian", "txt"],` using `//`
As follows
```
/**
 * Maps pluginIds to extensions that they use.
 * These extensions will be filtered out by default.
 *
 * @version 0.2.0
 * @author dbarenholz
 * @since 2022/08/13
 */
const otherExts = new Map([
    // https://github.com/deathau/cooklang-obsidian
    ["cooklang-obsidian", "cook"],
    // https://github.com/deathau/csv-obsidian
    ["csv-obsidian", "csv"],
    // https://github.com/caronchen/obsidian-chartsview-plugin
    ["obsidian-chartsview-plugin", "csv"],
    // https://github.com/Darakah/obsidian-fountain
    ["obsidian-fountain", "fountain"],
    // https://github.com/deathau/ini-obsidian
    ["ini-obsidian", "ini"],
    // https://github.com/deathau/txt-as-md-obsidian
    //["txt-as-md-obsidian", "txt"],
    // https://github.com/mkozhukharenko/mdx-as-md-obsidian
    ["mdx-as-md-obsidian", "mdx"],
    // https://github.com/ryanpcmcquen/obsidian-org-mode
    ["obsidian-org-mode", "org"],
    // https://github.com/tgrosinger/ledger-obsidian
    ["ledger-obsidian", "ledger"],
    // https://github.com/zsviczian/obsidian-excalidraw-plugin
    ["obsidian-excalidraw-plugin", "excalidraw"],
]);
```

Works great now for plain old `txt` files :)

**Comment by dbarenholz** [comment] 2023-06-06 20:27
Fixed in new version - I got the checking logic wrong because I was not familiar with JS maps - oops!

**Closed by dbarenholz** 2023-06-06 20:27 UTC

**Comment by dbarenholz** [comment] 2023-06-12 11:55
> I'm on Windows 10, and just updated the plugin to the latest version and restarted Obsidian. When I click a .text file it lets me open up and edit, but when I click a .txt file it opens up my default text editor. If I add txt to the list of extensions, it no longer opens up notepad, but it doesn't let me edit the .txt file.

@valgameiroconsulting Please make sure you have the latest version (right now, 0.3.0) and that it is enabled:
![image](https://github.com/dbarenholz/obsidian-plaintext/assets/25849034/84a22d6f-cd07-44e8-9616-accf8996ecdf)
And, make sure that in the settings you have the extension you wish to edit. I believe in your case this would be `.txt` and `.text`?
![image](https://github.com/dbarenholz/obsidian-plaintext/assets/25849034/bb1b24df-0709-4eeb-80b5-c563d74f538a)
After doing so, you should see a notice (pop-up) in the top-right of your screen that shows the extensions have indeed been updated.
![image](https://github.com/dbarenholz/obsidian-plaintext/assets/25849034/58b1a60a-6f8f-4e0b-aa06-6014d63806b1)

If all that works as I have described, then I don't know what the problem is. I can edit just fine?
![image](https://github.com/dbarenholz/obsidian-plaintext/assets/25849034/2d3260cb-376b-4a7e-87c7-9f0be663ef20)
